- hosts: nginx_waf_nap
  gather_facts: no
  become: yes
  vars_files:
    - keys.yml
  remote_user: admin #user on the ec2 instance
  tasks:
    - name: Gathering facts
      setup:

    - name: Set up NGINX Plus license
      block:
        - name: Create SSL directory
          file:
              path: /etc/ssl/nginx
              state: directory
              mode: 0755

        - name: Copy NGINX Plus certificate and license key
          copy:
              src: "{{ item }}"
              dest: /etc/ssl/nginx
              decrypt: true
              mode: 0444
          loop:
              - "{{ nginx_license['certificate'] }}"
              - "{{ nginx_license['key'] }}"
      when: ansible_facts['os_family'] != "Alpine"

    - name: (Debian/Ubuntu) Install dependencies
      apt:
        name: "{{ nginx_debian_dependencies }}"
        update_cache: true
        state: latest
      when: ansible_facts['os_family'] == "Debian"


    - name: Add Signing Key for NGINX 
      apt_key:
        url: https://cs.nginx.com/static/keys/nginx_signing.key
        id: ABF5BD827BD9BF62
        state: present

    - name: Add Signing Key for NGINX App Protect 
      apt_key:
        url: https://cs.nginx.com/static/keys/app-protect-security-updates.key
        id: A5F6473795E778F4
        state: present

    - name: NGINX Plus license verification
      blockinfile:
        path: /etc/apt/apt.conf.d/90pkgs-nginx
        create: true
        block: |
          Acquire::https::pkgs.nginx.com::Verify-Peer "true";
          Acquire::https::pkgs.nginx.com::Verify-Host "true";
          Acquire::https::pkgs.nginx.com::SslCert "/etc/ssl/nginx/nginx-repo.crt";
          Acquire::https::pkgs.nginx.com::SslKey "/etc/ssl/nginx/nginx-repo.key";
        state: "{{ nginx_license_status | default ('present') }}"
        mode: 0444

    - name: Add NGINX Plus Apt repository
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.nginx.com/plus/debian buster nginx-plus
        state: present
        filename: nginx-plus

    - name: Add NGINX App Protect Apt repository
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.nginx.com/app-protect/debian buster nginx-plus
        state: present
        filename: nginx-app-protect
  
    - name: Add NGINX App Protect sec updates repository
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.nginx.com/app-protect-security-updates/debian buster nginx-plus
        state: present
        filename: app-protect-security-updates

    - name: NGINX Plus license verification
      blockinfile:
        path: /etc/apt/apt.conf.d/90pkgs-nginx
        create: true
        block: |
          Acquire::https::pkgs.nginx.com::Verify-Peer "true";
          Acquire::https::pkgs.nginx.com::Verify-Host "true";
          Acquire::https::pkgs.nginx.com::SslCert "/etc/ssl/nginx/nginx-repo.crt";
          Acquire::https::pkgs.nginx.com::SslKey "/etc/ssl/nginx/nginx-repo.key";
        state: "{{ nginx_license_status | default ('present') }}"
        mode: 0444

    - name: Install NGINX App Protect
      apt:
        name: "app-protect"
        update_cache: true
        state: latest

    - name: Display IP for the NMS host from Inventory
      debug:
        var: hostvars[groups['nms'][0]].inventory_hostname

    - name: Install the NMS agent
      shell:
        cmd: "curl -k https://'{{ hostvars[groups['nms'][0]].inventory_hostname }}'/install/nginx-agent | sudo sh"
        creates: /lib/systemd/system/nginx-agent.service
      register: command_output

    - debug:
        var: command_output.stdout_lines
        
    - name: Start NGINX Service
      service:
        name: "{{ item }}"
        state: started
      with_items:
       - nginx
       - nginx-agent

    - name: Enable Services
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
       - nginx
       - nginx-agent
